"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TaskId(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_FIELD_NUMBER: builtins.int
    ACTOR_ID_FIELD_NUMBER: builtins.int
    TASK_UUID_FIELD_NUMBER: builtins.int
    service: builtins.str
    actor_id: builtins.str
    task_uuid: builtins.bytes
    def __init__(
        self,
        *,
        service: builtins.str = ...,
        actor_id: builtins.str = ...,
        task_uuid: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["actor_id", b"actor_id", "service", b"service", "task_uuid", b"task_uuid"]) -> None: ...

global___TaskId = TaskId

@typing_extensions.final
class WaitRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: builtins.int
    @property
    def task_id(self) -> global___TaskId: ...
    def __init__(
        self,
        *,
        task_id: global___TaskId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["task_id", b"task_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["task_id", b"task_id"]) -> None: ...

global___WaitRequest = WaitRequest

@typing_extensions.final
class WaitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSE_FIELD_NUMBER: builtins.int
    response: builtins.bytes
    def __init__(
        self,
        *,
        response: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["response", b"response"]) -> None: ...

global___WaitResponse = WaitResponse

@typing_extensions.final
class ListPendingTasksRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListPendingTasksRequest = ListPendingTasksRequest

@typing_extensions.final
class ListPendingTasksResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_IDS_FIELD_NUMBER: builtins.int
    @property
    def task_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TaskId]: ...
    def __init__(
        self,
        *,
        task_ids: collections.abc.Iterable[global___TaskId] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["task_ids", b"task_ids"]) -> None: ...

global___ListPendingTasksResponse = ListPendingTasksResponse
