"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TodoListMessage(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////
    State types.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name"]) -> None: ...

global___TodoListMessage = TodoListMessage

@typing_extensions.final
class TodoListsState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TODOLISTS_FIELD_NUMBER: builtins.int
    @property
    def todolists(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TodoListMessage]: ...
    def __init__(
        self,
        *,
        todolists: collections.abc.Iterable[global___TodoListMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["todolists", b"todolists"]) -> None: ...

global___TodoListsState = TodoListsState

@typing_extensions.final
class AddTodoListRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////
    Request and response types.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___AddTodoListRequest = AddTodoListRequest

@typing_extensions.final
class AddTodoListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    """The ID of the todolist that was just created."""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___AddTodoListResponse = AddTodoListResponse

@typing_extensions.final
class ListTodoListsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListTodoListsRequest = ListTodoListsRequest

@typing_extensions.final
class ListTodoListsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TODOLISTS_FIELD_NUMBER: builtins.int
    @property
    def todolists(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TodoListMessage]: ...
    def __init__(
        self,
        *,
        todolists: collections.abc.Iterable[global___TodoListMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["todolists", b"todolists"]) -> None: ...

global___ListTodoListsResponse = ListTodoListsResponse

@typing_extensions.final
class DeleteTodoListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___DeleteTodoListRequest = DeleteTodoListRequest

@typing_extensions.final
class DeleteTodoListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteTodoListResponse = DeleteTodoListResponse
