"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import resemble.v1alpha1.tasks_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UniqueText(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////
    State types.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    NUM_TIMES_FIELD_NUMBER: builtins.int
    to: builtins.str
    body: builtins.str
    create_time: builtins.str
    num_times: builtins.int
    def __init__(
        self,
        *,
        to: builtins.str = ...,
        body: builtins.str = ...,
        create_time: builtins.str = ...,
        num_times: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["body", b"body", "create_time", b"create_time", "num_times", b"num_times", "to", b"to"]) -> None: ...

global___UniqueText = UniqueText

@typing_extensions.final
class Pair(google.protobuf.message.Message):
    """message TwilioTextsState {
        repeated UniqueText uniquetexts = 1;
    }
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.int
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

global___Pair = Pair

@typing_extensions.final
class Text(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_FIELD_NUMBER: builtins.int
    FROM__FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    ACCEPTED_TIME_FIELD_NUMBER: builtins.int
    to: builtins.str
    from_: builtins.str
    body: builtins.str
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    accepted_time: builtins.str
    def __init__(
        self,
        *,
        to: builtins.str = ...,
        from_: builtins.str = ...,
        body: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        accepted_time: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["accepted_time", b"accepted_time", "body", b"body", "create_time", b"create_time", "from_", b"from_", "to", b"to"]) -> None: ...

global___Text = Text

@typing_extensions.final
class TwilioTextsState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXTS_TO_SEND_FIELD_NUMBER: builtins.int
    TEXTS_ACCEPTED_FIELD_NUMBER: builtins.int
    @property
    def texts_to_send(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Text]: ...
    @property
    def texts_accepted(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Text]: ...
    def __init__(
        self,
        *,
        texts_to_send: collections.abc.Iterable[global___Text] | None = ...,
        texts_accepted: collections.abc.Iterable[global___Text] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["texts_accepted", b"texts_accepted", "texts_to_send", b"texts_to_send"]) -> None: ...

global___TwilioTextsState = TwilioTextsState

@typing_extensions.final
class CreateTwilioTextRequest(google.protobuf.message.Message):
    """//////////////////////////////////////////////////////////////////////
    Request and response types.

    string to = 1;
    string body = 2;
    string create_time = 3;
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateTwilioTextRequest = CreateTwilioTextRequest

@typing_extensions.final
class CreateTwilioTextResponse(google.protobuf.message.Message):
    """resemble.v1alpha1.TaskId reminder_text_task_id = 1;"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateTwilioTextResponse = CreateTwilioTextResponse

@typing_extensions.final
class AddTextRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    to: builtins.str
    body: builtins.str
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        to: builtins.str = ...,
        body: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["create_time", b"create_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["body", b"body", "create_time", b"create_time", "to", b"to"]) -> None: ...

global___AddTextRequest = AddTextRequest

@typing_extensions.final
class AddTextResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMINDER_TEXT_TASK_ID_FIELD_NUMBER: builtins.int
    @property
    def reminder_text_task_id(self) -> resemble.v1alpha1.tasks_pb2.TaskId: ...
    def __init__(
        self,
        *,
        reminder_text_task_id: resemble.v1alpha1.tasks_pb2.TaskId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["reminder_text_task_id", b"reminder_text_task_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["reminder_text_task_id", b"reminder_text_task_id"]) -> None: ...

global___AddTextResponse = AddTextResponse

@typing_extensions.final
class ListTextsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ListTextsRequest = ListTextsRequest

@typing_extensions.final
class ListTextsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UNIQUETEXTS_FIELD_NUMBER: builtins.int
    @property
    def uniquetexts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UniqueText]: ...
    def __init__(
        self,
        *,
        uniquetexts: collections.abc.Iterable[global___UniqueText] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uniquetexts", b"uniquetexts"]) -> None: ...

global___ListTextsResponse = ListTextsResponse

@typing_extensions.final
class TwilioReminderTextTaskRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_TO_SEND_FIELD_NUMBER: builtins.int
    @property
    def text_to_send(self) -> global___Text:
        """string to = 1;
        string body = 2;
        string create_time = 3;
        int32 num_times = 4;
        """
    def __init__(
        self,
        *,
        text_to_send: global___Text | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["text_to_send", b"text_to_send"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["text_to_send", b"text_to_send"]) -> None: ...

global___TwilioReminderTextTaskRequest = TwilioReminderTextTaskRequest
